# Generated by Django 5.1 on 2024-08-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("road_address", models.CharField(max_length=255)),
                ("jibun_address", models.CharField(max_length=255)),
                ("has_disabled_toilet", models.BooleanField(default=False)),
                ("contact_number", models.CharField(max_length=50)),
                ("opening_hours", models.CharField(max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("waste_treatment", models.CharField(max_length=50)),
                ("cctv", models.BooleanField(default=False)),
                (
                    "remodeling_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_date", models.CharField(max_length=50)),
            ],
        ),
    ]
